#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2022 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

# Exit immediately on each error and unset variable;
# see: https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -Eeuo pipefail
#set -Eeu

# For human readability, we want to display the class and sub-class titles.
# We get them from the "CPC Title List" download found on this site:
# https://www.cooperativepatentclassification.org/cpcSchemeAndDefinitions/bulk
# Which at the time of our last download was:
ARCH_URL="https://www.cooperativepatentclassification.org/sites/default/files/cpc/bulk/CPCTitleList202205.zip"
EX_DIR="output/CPCTitleListLatest"
ARCH_FILE="$(basename "$ARCH_URL")"
OUT_FILE="output/cpc-titles.csv"

mkdir -p "$(dirname "$EX_DIR")"
mkdir -p "$(dirname "$ARCH_FILE")"
mkdir -p "$(dirname "$OUT_FILE")"

# Download the archive
if ! [ -e "$ARCH_FILE" ]
then
	echo "Downloading archive ..."
	curl --silent --output "$ARCH_FILE" "$ARCH_URL"
fi

# Extract the archive
echo "Extracting archive ..."
rm -Rf "${EX_DIR:?}/"*
unzip -q -d "$EX_DIR" "$ARCH_FILE"

echo "Converting data ..."
# Convert Windows to UNIX EOL (end-of-line) characters
sed -i 's/\r$//' output/CPCTitleListLatest/cpc-section-*.txt

# Filter out only main and sub titles,
# and convert to CSV format
grep -r --no-filename '^[A-Z]\([0-9][0-9]\)\?[[:space:]]' output/CPCTitleListLatest/ \
	| sed -e 's|^\([A-Z]\([0-9][0-9]\)\?\)[[:space:]]\+\(.*\)$|\"\1\",\"\3"|' \
	> "$OUT_FILE"

echo "CPC Titles successfully extracted to '$OUT_FILE'."
echo "done."
