#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2022 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

# Exit immediately on each error and unset variable;
# see: https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -Eeuo pipefail
#set -Eeu

mkdir -p output

jupyter nbconvert \
	--to pdf \
	--output-dir=output \
	--no-input \
	report.ipynb
jupyter nbconvert \
	--to html \
	--output-dir=output \
	--no-input \
	report.ipynb

echo "Successfully created 'output/report.pdf' and 'output/report.html'!"

