#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2022 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

# Exit immediately on each error and unset variable;
# see: https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -Eeuo pipefail
#set -Eeu

title="LOSH Report 2022"

mkdir -p output/imgs

function dl_img() {

	local url="$1"
	local file
	file="output/imgs/$(basename "$url")"

	if ! [ -f "$file" ]
	then
		curl "$url" --output "$file"
	fi
}

dl_img "https://mntre.com/media/reform_v2_images/reform_v2_prototype_top.jpg"
dl_img "https://openflexure.org/assets/ds-photos/ds_v1.2.0_wide.jpg"
dl_img "https://upload.wikimedia.org/wikipedia/commons/7/73/Upsatinspace.jpg"

cp report.ipynb "$title.ipynb"
for outfmt in pdf html markdown
do
	jupyter nbconvert \
		--to "$outfmt" \
		--output-dir=output \
		--no-input \
		"$title.ipynb"
done
rm "$title.ipynb"

for rep in "output/$title."*
do
	mv "$rep" "${rep/$title/report}"
done

echo
echo "Successfully created:"
ls -1 "output/report."*


