#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2022 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

# Exit immediately on each error and unset variable;
# see: https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -Eeuo pipefail
#set -Eeu

mkdir -p output

for outfmt in pdf html markdown
do
	jupyter nbconvert \
		--to "$outfmt" \
		--output-dir=output \
		--no-input \
		report.ipynb
done

echo
echo "Successfully created:"
ls -1 "output/report."*


